/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.dkozak.profiler.client

import io.dkozak.profiler.scanner.Library

fun main(args: Array<String>) {
    println(Library().greeting)
}
