/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.dkozak.profiler.scanner

class Library {
    val greeting: String
        get() {
            return "Hello world."
        }
}
