/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.dkozak.profiler.scanner

import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
    @Test
    fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertEquals(classUnderTest.greeting, "Hello world from the lib :)")
    }
}
